INCLUDE(CMakeForceCompiler)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR MSP430G2001)

#set(triple arm-none-aeabi)

SET(CMAKE_FIND_ROOT_PATH  "C:/Program Files/IAR Systems/Embedded Workbench 7.3/430")

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)


set(CMAKE_C_COMPILER "${CMAKE_FIND_ROOT_PATH}/bin/icc430.exe")
#set(CMAKE_C_COMPILER_TARGET ${triple})

#set(CMAKE_C_LINK_EXECUTABLE "${CMAKE_FIND_ROOT_PATH}/bin/xlink.exe")
set(CMAKE_CXX_COMPILER "${CMAKE_FIND_ROOT_PATH}/bin/icc430.exe")
#set(CMAKE_CXX_COMPILER_TARGET ${triple})

string(REPLACE "MSP" "lnk" LNK_FILE ${CMAKE_SYSTEM_PROCESSOR})

SET(CMAKE_C_FLAGS_INIT "--strict --debug -On --dlib --dlib_config=\"${CMAKE_FIND_ROOT_PATH}/lib/dlib/dl430ff.h\" " CACHE STRING "" FORCE)
SET(CMAKE_C_LINK_FLAGS "\"${CMAKE_FIND_ROOT_PATH}/lib/dlib/dl430ff.r43\" \
						 -rt -D_STACK_SIZE=80 -D_DATA16_HEAP_SIZE=80 \
						-I\"${CMAKE_FIND_ROOT_PATH}/config/linker\" \
						-f ${LNK_FILE}.xcl" CACHE STRING "" FORCE)

set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_C_COMPILER_WORKS TRUE)

set(CMAKE_C_COMPILE_OBJECT             "<CMAKE_C_COMPILER> <SOURCE> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT>")
set(CMAKE_C_CREATE_PREPROCESSED_SOURCE "<CMAKE_C_COMPILER> <SOURCE> <DEFINES> <INCLUDES> <FLAGS> --preprocess=cnl <PREPROCESSED_SOURCE>")
set(CMAKE_C_CREATE_ASSEMBLY_SOURCE     "<CMAKE_C_COMPILER> <SOURCE> <DEFINES> <INCLUDES> <FLAGS> -lAH <ASSEMBLY_SOURCE> -o <OBJECT>.dummy")

set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <OBJECTS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <LINK_LIBRARIES> -o <TARGET>.d43")
set(CMAKE_C_CREATE_STATIC_LIBRARY "<CMAKE_AR> <TARGET> --create <LINK_FLAGS> <OBJECTS> ")
 
add_definitions(-D__${CMAKE_SYSTEM_PROCESSOR}__)

#set(CMAKE_C90_STANDARD_COMPILE_OPTION --c89)
#set(CMAKE_C90_EXTENSION_COMPILE_OPTION --c89 -e)
#set(CMAKE_C99_STANDARD_COMPILE_OPTION "")
#set(CMAKE_C99_EXTENSION_COMPILE_OPTION -e)

find_program(CMAKE_IAR_LINKER xlink HINTS "${CMAKE_FIND_ROOT_PATH}/bin" )
find_program(CMAKE_IAR_AR xar HINTS "${CMAKE_FIND_ROOT_PATH}/bin" )

set(CMAKE_LINKER "${CMAKE_IAR_LINKER}" CACHE FILEPATH "The IAR linker" FORCE)
set(CMAKE_AR "${CMAKE_IAR_AR}" CACHE FILEPATH "The IAR archiver" FORCE)